// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: bid/v1/model.proto

package bidpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bid struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AuctionId     string                 `protobuf:"bytes,2,opt,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty"`
	QtyInCents    int32                  `protobuf:"varint,3,opt,name=qty_in_cents,json=qtyInCents,proto3" json:"qty_in_cents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bid) Reset() {
	*x = Bid{}
	mi := &file_bid_v1_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bid) ProtoMessage() {}

func (x *Bid) ProtoReflect() protoreflect.Message {
	mi := &file_bid_v1_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bid.ProtoReflect.Descriptor instead.
func (*Bid) Descriptor() ([]byte, []int) {
	return file_bid_v1_model_proto_rawDescGZIP(), []int{0}
}

func (x *Bid) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Bid) GetAuctionId() string {
	if x != nil {
		return x.AuctionId
	}
	return ""
}

func (x *Bid) GetQtyInCents() int32 {
	if x != nil {
		return x.QtyInCents
	}
	return 0
}

type Auction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuctionId     string                 `protobuf:"bytes,1,opt,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty"`
	Item          string                 `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	Bids          []*Bid                 `protobuf:"bytes,3,rep,name=bids,proto3" json:"bids,omitempty"`
	EndsAt        *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=ends_at,json=endsAt,proto3" json:"ends_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Auction) Reset() {
	*x = Auction{}
	mi := &file_bid_v1_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Auction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auction) ProtoMessage() {}

func (x *Auction) ProtoReflect() protoreflect.Message {
	mi := &file_bid_v1_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auction.ProtoReflect.Descriptor instead.
func (*Auction) Descriptor() ([]byte, []int) {
	return file_bid_v1_model_proto_rawDescGZIP(), []int{1}
}

func (x *Auction) GetAuctionId() string {
	if x != nil {
		return x.AuctionId
	}
	return ""
}

func (x *Auction) GetItem() string {
	if x != nil {
		return x.Item
	}
	return ""
}

func (x *Auction) GetBids() []*Bid {
	if x != nil {
		return x.Bids
	}
	return nil
}

func (x *Auction) GetEndsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndsAt
	}
	return nil
}

var File_bid_v1_model_proto protoreflect.FileDescriptor

const file_bid_v1_model_proto_rawDesc = "" +
	"\n" +
	"\x12bid/v1/model.proto\x12\x06bid.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"_\n" +
	"\x03Bid\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"auction_id\x18\x02 \x01(\tR\tauctionId\x12 \n" +
	"\fqty_in_cents\x18\x03 \x01(\x05R\n" +
	"qtyInCents\"\x92\x01\n" +
	"\aAuction\x12\x1d\n" +
	"\n" +
	"auction_id\x18\x01 \x01(\tR\tauctionId\x12\x12\n" +
	"\x04item\x18\x02 \x01(\tR\x04item\x12\x1f\n" +
	"\x04bids\x18\x03 \x03(\v2\v.bid.v1.BidR\x04bids\x123\n" +
	"\aends_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x06endsAtB>Z<github.com/sverdejot/grpc-streams/internal/api/grpc/v1;bidpbb\x06proto3"

var (
	file_bid_v1_model_proto_rawDescOnce sync.Once
	file_bid_v1_model_proto_rawDescData []byte
)

func file_bid_v1_model_proto_rawDescGZIP() []byte {
	file_bid_v1_model_proto_rawDescOnce.Do(func() {
		file_bid_v1_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bid_v1_model_proto_rawDesc), len(file_bid_v1_model_proto_rawDesc)))
	})
	return file_bid_v1_model_proto_rawDescData
}

var file_bid_v1_model_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_bid_v1_model_proto_goTypes = []any{
	(*Bid)(nil),                   // 0: bid.v1.Bid
	(*Auction)(nil),               // 1: bid.v1.Auction
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_bid_v1_model_proto_depIdxs = []int32{
	0, // 0: bid.v1.Auction.bids:type_name -> bid.v1.Bid
	2, // 1: bid.v1.Auction.ends_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_bid_v1_model_proto_init() }
func file_bid_v1_model_proto_init() {
	if File_bid_v1_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bid_v1_model_proto_rawDesc), len(file_bid_v1_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bid_v1_model_proto_goTypes,
		DependencyIndexes: file_bid_v1_model_proto_depIdxs,
		MessageInfos:      file_bid_v1_model_proto_msgTypes,
	}.Build()
	File_bid_v1_model_proto = out.File
	file_bid_v1_model_proto_goTypes = nil
	file_bid_v1_model_proto_depIdxs = nil
}
