// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: bid/v1/request.proto

package bidpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateBidRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AuctionId       string                 `protobuf:"bytes,2,opt,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty"`
	QuantityInCents int32                  `protobuf:"varint,3,opt,name=quantity_in_cents,json=quantityInCents,proto3" json:"quantity_in_cents,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateBidRequest) Reset() {
	*x = CreateBidRequest{}
	mi := &file_bid_v1_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBidRequest) ProtoMessage() {}

func (x *CreateBidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bid_v1_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBidRequest.ProtoReflect.Descriptor instead.
func (*CreateBidRequest) Descriptor() ([]byte, []int) {
	return file_bid_v1_request_proto_rawDescGZIP(), []int{0}
}

func (x *CreateBidRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateBidRequest) GetAuctionId() string {
	if x != nil {
		return x.AuctionId
	}
	return ""
}

func (x *CreateBidRequest) GetQuantityInCents() int32 {
	if x != nil {
		return x.QuantityInCents
	}
	return 0
}

type GetBidsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuctionId     string                 `protobuf:"bytes,1,opt,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBidsRequest) Reset() {
	*x = GetBidsRequest{}
	mi := &file_bid_v1_request_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBidsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBidsRequest) ProtoMessage() {}

func (x *GetBidsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bid_v1_request_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBidsRequest.ProtoReflect.Descriptor instead.
func (*GetBidsRequest) Descriptor() ([]byte, []int) {
	return file_bid_v1_request_proto_rawDescGZIP(), []int{1}
}

func (x *GetBidsRequest) GetAuctionId() string {
	if x != nil {
		return x.AuctionId
	}
	return ""
}

var File_bid_v1_request_proto protoreflect.FileDescriptor

const file_bid_v1_request_proto_rawDesc = "" +
	"\n" +
	"\x14bid/v1/request.proto\x12\x06bid.v1\"v\n" +
	"\x10CreateBidRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"auction_id\x18\x02 \x01(\tR\tauctionId\x12*\n" +
	"\x11quantity_in_cents\x18\x03 \x01(\x05R\x0fquantityInCents\"/\n" +
	"\x0eGetBidsRequest\x12\x1d\n" +
	"\n" +
	"auction_id\x18\x01 \x01(\tR\tauctionIdB>Z<github.com/sverdejot/grpc-streams/internal/api/grpc/v1;bidpbb\x06proto3"

var (
	file_bid_v1_request_proto_rawDescOnce sync.Once
	file_bid_v1_request_proto_rawDescData []byte
)

func file_bid_v1_request_proto_rawDescGZIP() []byte {
	file_bid_v1_request_proto_rawDescOnce.Do(func() {
		file_bid_v1_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bid_v1_request_proto_rawDesc), len(file_bid_v1_request_proto_rawDesc)))
	})
	return file_bid_v1_request_proto_rawDescData
}

var file_bid_v1_request_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_bid_v1_request_proto_goTypes = []any{
	(*CreateBidRequest)(nil), // 0: bid.v1.CreateBidRequest
	(*GetBidsRequest)(nil),   // 1: bid.v1.GetBidsRequest
}
var file_bid_v1_request_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bid_v1_request_proto_init() }
func file_bid_v1_request_proto_init() {
	if File_bid_v1_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bid_v1_request_proto_rawDesc), len(file_bid_v1_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bid_v1_request_proto_goTypes,
		DependencyIndexes: file_bid_v1_request_proto_depIdxs,
		MessageInfos:      file_bid_v1_request_proto_msgTypes,
	}.Build()
	File_bid_v1_request_proto = out.File
	file_bid_v1_request_proto_goTypes = nil
	file_bid_v1_request_proto_depIdxs = nil
}
