// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: bid/v1/response.proto

package bidpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateBidResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBidResponse) Reset() {
	*x = CreateBidResponse{}
	mi := &file_bid_v1_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBidResponse) ProtoMessage() {}

func (x *CreateBidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bid_v1_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBidResponse.ProtoReflect.Descriptor instead.
func (*CreateBidResponse) Descriptor() ([]byte, []int) {
	return file_bid_v1_response_proto_rawDescGZIP(), []int{0}
}

type GetBidsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bid           *Bid                   `protobuf:"bytes,1,opt,name=bid,proto3" json:"bid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBidsResponse) Reset() {
	*x = GetBidsResponse{}
	mi := &file_bid_v1_response_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBidsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBidsResponse) ProtoMessage() {}

func (x *GetBidsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bid_v1_response_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBidsResponse.ProtoReflect.Descriptor instead.
func (*GetBidsResponse) Descriptor() ([]byte, []int) {
	return file_bid_v1_response_proto_rawDescGZIP(), []int{1}
}

func (x *GetBidsResponse) GetBid() *Bid {
	if x != nil {
		return x.Bid
	}
	return nil
}

var File_bid_v1_response_proto protoreflect.FileDescriptor

const file_bid_v1_response_proto_rawDesc = "" +
	"\n" +
	"\x15bid/v1/response.proto\x12\x06bid.v1\x1a\x12bid/v1/model.proto\"\x13\n" +
	"\x11CreateBidResponse\"0\n" +
	"\x0fGetBidsResponse\x12\x1d\n" +
	"\x03bid\x18\x01 \x01(\v2\v.bid.v1.BidR\x03bidB>Z<github.com/sverdejot/grpc-streams/internal/api/grpc/v1;bidpbb\x06proto3"

var (
	file_bid_v1_response_proto_rawDescOnce sync.Once
	file_bid_v1_response_proto_rawDescData []byte
)

func file_bid_v1_response_proto_rawDescGZIP() []byte {
	file_bid_v1_response_proto_rawDescOnce.Do(func() {
		file_bid_v1_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bid_v1_response_proto_rawDesc), len(file_bid_v1_response_proto_rawDesc)))
	})
	return file_bid_v1_response_proto_rawDescData
}

var file_bid_v1_response_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_bid_v1_response_proto_goTypes = []any{
	(*CreateBidResponse)(nil), // 0: bid.v1.CreateBidResponse
	(*GetBidsResponse)(nil),   // 1: bid.v1.GetBidsResponse
	(*Bid)(nil),               // 2: bid.v1.Bid
}
var file_bid_v1_response_proto_depIdxs = []int32{
	2, // 0: bid.v1.GetBidsResponse.bid:type_name -> bid.v1.Bid
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_bid_v1_response_proto_init() }
func file_bid_v1_response_proto_init() {
	if File_bid_v1_response_proto != nil {
		return
	}
	file_bid_v1_model_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bid_v1_response_proto_rawDesc), len(file_bid_v1_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bid_v1_response_proto_goTypes,
		DependencyIndexes: file_bid_v1_response_proto_depIdxs,
		MessageInfos:      file_bid_v1_response_proto_msgTypes,
	}.Build()
	File_bid_v1_response_proto = out.File
	file_bid_v1_response_proto_goTypes = nil
	file_bid_v1_response_proto_depIdxs = nil
}
