// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: bid/v1/service.proto

package bidpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_bid_v1_service_proto protoreflect.FileDescriptor

const file_bid_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x14bid/v1/service.proto\x12\x06bid.v1\x1a\x14bid/v1/request.proto\x1a\x15bid/v1/response.proto2\x94\x01\n" +
	"\x0eAuctionService\x12B\n" +
	"\tCreateBid\x12\x18.bid.v1.CreateBidRequest\x1a\x19.bid.v1.CreateBidResponse\"\x00\x12>\n" +
	"\aGetBids\x12\x16.bid.v1.GetBidsRequest\x1a\x17.bid.v1.GetBidsResponse\"\x000\x01B>Z<github.com/sverdejot/grpc-streams/internal/api/grpc/v1;bidpbb\x06proto3"

var file_bid_v1_service_proto_goTypes = []any{
	(*CreateBidRequest)(nil),  // 0: bid.v1.CreateBidRequest
	(*GetBidsRequest)(nil),    // 1: bid.v1.GetBidsRequest
	(*CreateBidResponse)(nil), // 2: bid.v1.CreateBidResponse
	(*GetBidsResponse)(nil),   // 3: bid.v1.GetBidsResponse
}
var file_bid_v1_service_proto_depIdxs = []int32{
	0, // 0: bid.v1.AuctionService.CreateBid:input_type -> bid.v1.CreateBidRequest
	1, // 1: bid.v1.AuctionService.GetBids:input_type -> bid.v1.GetBidsRequest
	2, // 2: bid.v1.AuctionService.CreateBid:output_type -> bid.v1.CreateBidResponse
	3, // 3: bid.v1.AuctionService.GetBids:output_type -> bid.v1.GetBidsResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bid_v1_service_proto_init() }
func file_bid_v1_service_proto_init() {
	if File_bid_v1_service_proto != nil {
		return
	}
	file_bid_v1_request_proto_init()
	file_bid_v1_response_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bid_v1_service_proto_rawDesc), len(file_bid_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bid_v1_service_proto_goTypes,
		DependencyIndexes: file_bid_v1_service_proto_depIdxs,
	}.Build()
	File_bid_v1_service_proto = out.File
	file_bid_v1_service_proto_goTypes = nil
	file_bid_v1_service_proto_depIdxs = nil
}
